# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mobiventarium' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mobiventarium
  pod 'Firebase/Core'
  pod 'Firebase/Auth'

  target 'mobiventariumTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'mobiventarium-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mobiventarium-tvOS

  target 'mobiventarium-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
