# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mobiventarium' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mobiventarium
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore', '~>5.0.0'
  
  pod 'React', :path => '../node_modules/react-native'
  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'
  
  
  # See http://facebook.github.io/react-native/docs/integration-with-existing-apps.html#configuring-cocoapods-dependencies
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'Core',
  'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
  'RCTText',
  'RCTNetwork',
  'RCTWebSocket', # Needed for debugging
  'RCTAnimation', # Needed for FlatList and animations running on native UI thread
  # Add any other subspecs you want to use in your project
  ]
  
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  
  # Third party deps podspec link
  pod 'react-native-camera', path: '../node_modules/react-native-camera'
  
  post_install do |installer|
      installer.pods_project.targets.each do |target|
          if target.name == "React"
              target.remove_from_project
          end
      end
  end

  target 'mobiventariumTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'mobiventarium-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mobiventarium-tvOS

  target 'mobiventarium-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
